TOP=..

LIBRARY=shelisp.dll
LIBRARY_SOURCES=$(wildcard *.cs)

# this should live in $(TOP)/build/config.mk
#EXTRA_FLAGS += -define:DEBUG
#EXTRA_FLAGS += -define:EVAL_SPEW

include $(TOP)/build/build.mk
